name: 'Build, Publish and Release'

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]'
  workflow_dispatch:

jobs:
  build-publish-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - name: Set up yarn (Node 20)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      ## Test, build and publish

      - name: Test, build and publish package
        run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
